version: '3.8'

services:
  wildfly:
    build: .
    container_name: jakarta-products-api
    ports:
      - "8080:8080"
      - "9990:9990"  # Port d'administration WildFly
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - products-network
    restart: unless-stopped

networks:
  products-network:
    driver: bridge
