services:
  postgres:
    image: postgres:16-alpine
    container_name: products-postgres
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U products_user -d productsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring-products-api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productsdb
      SPRING_DATASOURCE_USERNAME: products_user
      SPRING_DATASOURCE_PASSWORD: products_pass
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
